version: '3.3'
services:
    # rabbitmq:
    #     container_name: same-rabbit
    #     environment:
    #         - RABBITMQ_DEFAULT_USER=archio
    #         - RABBITMQ_DEFAULT_PASS=archio
    #     # volumes:
    #     #     - '/wellingtonoliveira@Wellingtons-MacBook-Air infradev/data:/var/lib/rabbitmq'
    #     ports:
    #         - '5672:5672'
    #         - '15672:15672'
    #     image: 'rabbitmq:management'

    ocr:
        image: archiocloud/develop:archio-ocrlocal-v1
        container_name: ocr
        ports:
            - '7000:7000'
