version: "3"
services:
  # archio-rabbitmq:
  #   container_name: archio-rabbit
  #   environment:
  #       - RABBITMQ_DEFAULT_USER=archio
  #       - RABBITMQ_DEFAULT_PASS=archio
  #   volumes:
  #       - '/home/g2013wcoliveira/rabbitmq/data:/var/lib/rabbitmq'
  #   ports:
  #       - '5673:5672'
  #       - '15673:15672'
  #   image: 'rabbitmq:management'
  api-main:
    image: archiocloud/archiomaster:08
    ports:
      - "3000:3000"
    # depends_on: 
    #   - archio-rabbitmq
  # api-export:
  #   image: archiocloud/develop:archio-exportsearch-v1
  #   ports:
  #   - "3003:3003"  
  # api-cron:
  #   image: archiocloud/develop:archio-cron-v1
  #   ports:
  #   - "3001:3001"  
  # # api-import-volumes:y
  #   image: wellingtondevops/dev-archio-import-volume:v6
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - archio-rabbitmq
  #     - api-main

      
      
      
  
         

  
