version: '3.3'
services:
    rabbitmq:
        container_name: same-rabbit
        environment:
            - RABBITMQ_DEFAULT_USER=archio
            - RABBITMQ_DEFAULT_PASS=archio
        # volumes:
        #     - '/wellingtonoliveira@Wellingtons-MacBook-Air infradev/data:/var/lib/rabbitmq'
        ports:
            - '5672:5672'
            - '15672:15672'
        image: 'rabbitmq:management'
    # api-processs:
    #     image: archiocloud/develop:process-index-v05  
    redis:
        image: redis
        container_name: cache
        ports:
            - '6379:6379'
